name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
     - name: Deploy to Netlify
                                                     run
                              - name: Rollback on Failure
                     if: failure()
                      run: |
                        echo "Rolling back to previous version..."
                        # Add rollback commands herep    x netlify deploy --prod --dir=build --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID


    - name: Build proj
on:
  release:
    types: [published]
    name: My Workflow

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secretNETLIFY_AUTH_TOKE_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
